# Generated by Django 5.2.1 on 2025-05-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('url_path', models.CharField(max_length=20)),
                ('is_running', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
