# Generated by Django 5.2.1 on 2025-05-26 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConnectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_from', to='main.appinstancemodel')),
                ('instance_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_to', to='main.appinstancemodel')),
            ],
        ),
    ]
