# Generated by Django 5.2.1 on 2025-06-03 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appconnectionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=20, verbose_name='Organization name')),
            ],
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='app_name',
            field=models.CharField(max_length=20, verbose_name='App name'),
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='url_path',
            field=models.CharField(blank=True, help_text='Leave empty to match app name', max_length=20, verbose_name='URL path'),
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='owner_org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.organizationentity'),
            preserve_default=False,
        ),
    ]
