# Generated by Django 4.2.21 on 2025-06-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_organizationentity_alter_appinstancemodel_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='api_token',
            field=models.CharField(default='asdf', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='owner_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organizationentity', verbose_name='Owner organization'),
        ),
    ]
