# Generated by Django 4.2.23 on 2025-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appinstancemodel_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='app_title',
            field=models.CharField(default='asd', help_text='e.g. "ADDMAN EXT" or "ADDMAN OEM B"', max_length=20, verbose_name='App title'),
            preserve_default=False,
        ),
    ]
