# Generated by Django 4.2.21 on 2025-06-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appinstancemodel_app_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationentity',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationentity',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
