# Generated by Django 4.2.23 on 2025-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_organizationentity_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='container_image',
            field=models.CharField(default='addman', help_text='e.g. addman', max_length=50, verbose_name='Container image'),
            preserve_default=False,
        ),
    ]
