# Generated by Django 4.2.23 on 2025-06-19 10:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_appinstancemodel_container_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(path=main.models.instance_template_files)),
            ],
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='template_files',
            field=models.ManyToManyField(to='main.templatefilemodel'),
        ),
    ]
