# Generated by Django 4.2.23 on 2025-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_templatefilemodel_appinstancemodel_template_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefilemodel',
            name='filepath',
            field=models.CharField(max_length=512),
        ),
    ]
