# Generated by Django 4.2.23 on 2025-06-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_templatefilemodel_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefilemodel',
            name='filename',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
