# Generated by Django 4.2.21 on 2025-06-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_templatefilemodel_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstancemodel',
            name='app_title',
        ),
        migrations.RemoveField(
            model_name='appinstancemodel',
            name='container_image',
        ),
    ]
