# Generated by Django 4.2.21 on 2025-06-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_appinstancemodel_app_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='using_compose',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
