# Generated by Django 4.2.21 on 2025-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_appinstancemodel_using_compose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstancemodel',
            name='is_running',
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='status',
            field=models.IntegerField(choices=[('RUNNING', 1), ('STOPPED', 2), ('MISSING', 3), ('REMOVED', 4), ('ERROR', 5)], default=2),
            preserve_default=False,
        ),
    ]
