# Generated by Django 4.2.21 on 2025-07-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_appinstancemodel_is_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='instance_directories',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='instance_environment_variables',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='instance_labels',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='instance_volumes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
