# Generated by Django 4.2.21 on 2025-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_appinstancemodel_instance_directories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPresetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset_name', models.CharField(max_length=20, verbose_name='Preset name')),
                ('instance_directories', models.CharField(blank=True, max_length=1024)),
                ('instance_labels', models.CharField(blank=True, max_length=1024)),
                ('instance_volumes', models.CharField(blank=True, max_length=1024)),
                ('instance_environment_variables', models.CharField(blank=True, max_length=1024)),
                ('template_files', models.ManyToManyField(to='main.templatefilemodel')),
            ],
        ),
    ]
