# Generated by Django 4.2.21 on 2025-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_apppresetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppresetmodel',
            name='container_image',
            field=models.CharField(default='path-deployments-app', max_length=20),
            preserve_default=False,
        ),
    ]
