# Generated by Django 4.2.21 on 2025-07-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_apppresetmodel_container_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, verbose_name='Location name')),
                ('code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('info', models.CharField(max_length=500, verbose_name='Additional information')),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationentity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organizationentity',
            name='longitude',
        ),
        migrations.AddField(
            model_name='organizationentity',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.locationmodel'),
            preserve_default=False,
        ),
    ]
