# Generated by Django 4.2.21 on 2025-07-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_locationmodel_remove_organizationentity_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinstancemodel',
            name='owner_org',
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='owner_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.organizationentity', verbose_name='Owner organization'),
            preserve_default=False,
        ),
    ]
