# Generated by Django 4.2.21 on 2025-07-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_appinstancemodel_owner_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='container_image',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appinstancemodel',
            name='container_user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='info',
            field=models.CharField(blank=True, max_length=500, verbose_name='Additional information'),
        ),
    ]
