# Generated by Django 4.2.21 on 2025-07-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_appinstancemodel_container_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppresetmodel',
            name='container_user',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
