# Generated by Django 4.2.21 on 2025-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_apppresetmodel_container_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='status',
            field=models.IntegerField(choices=[('RUNNING', 1), ('PAUSED', 2), ('STOPPED', 3), ('REMOVED', 4), ('MISSING', 5), ('ERROR', 6)]),
        ),
    ]
