# Generated by Django 4.2.23 on 2025-07-29 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_locationmodel_status_alter_appinstancemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstancemodel',
            name='api_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='app_name',
            field=models.CharField(help_text="Allowed characters: A-Z, -, _. Don't use spaces or numbers. Must be at least 3 characters long.", max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z_-]{3,}$')], verbose_name='App name'),
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='location',
            field=models.ForeignKey(help_text='Attach this application to a location', on_delete=django.db.models.deletion.CASCADE, to='main.locationmodel'),
        ),
        migrations.AlterField(
            model_name='appinstancemodel',
            name='url_path',
            field=models.CharField(blank=True, help_text='Leave empty to match app name. Allowed characters: A-Z, -, _. Must be at least 3 characters long.', max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z_-]{3,}$')], verbose_name='URL path'),
        ),
    ]
