# Generated by Django 4.2.21 on 2025-07-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_appinstancemodel_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstancemodel',
            name='info',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
