# Generated by Django 4.2.21 on 2025-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_appinstancemodel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinstancemodel',
            name='template_files',
            field=models.ManyToManyField(blank=True, to='main.templatefilemodel'),
        ),
    ]
